// Angular/src/app/user-view/user-view.component.ts
import { Component, OnInit } from '@angular/core';
import { ContextService, ApscService, I18nService } from '@aps';
import {UsersService} from "../users.service";

function getStatus(user) {
    switch (user.aps.status) {
        case "aps:proto":
            return "creating";
        case "aps:configuring":
        case "aps:provisioning":
            return "updating";
        case "aps:unprovisioning":
            return "deleting";
        case "aps:deleted":
            return "deleted";
        case "aps:ready":
            if (!Array.isArray(user.services)) {
                console.warn("[ERROR] UserStatus cant resolve user services status: they were not loaded to model");
            } else
            if (user.services.some(function(service) {
                return	"aps:updating" === service.aps.status ||
                    "aps:deleting" === service.aps.status ||
                    "aps:provisioning" === service.aps.status ||
                    "aps:configuring" === service.aps.status;
            })) {
                return "configuringServices";
            }

        default:
            if (user.disabled) {
                return "disabled";
            }

            if (user.locked) {
                return "locked";
            }

            if (!!user.invitationDate) {
                return "invited";
            }
    }

    return "ready";
}

function calculateDiff(invitationDate){
    const currentDate = new Date();
    invitationDate = new Date(invitationDate);
    const timeDiff = currentDate.getTime() - invitationDate.getTime();
    return Math.ceil(timeDiff / (1000 * 3600));
}

@Component({
    selector: 'user-view',
    templateUrl: './user-view.component.html'
})
export class UserViewComponent implements OnInit {
    private _: (text: string) => string;
    private hasLoginAsPermission: boolean;
    private hasManagePrivilege: boolean;
    private status: string;
    private isNotificationEmailHidden: boolean;
    private isEmailHidden: boolean;
    private isCurrentUser: boolean;
    private isAdmin: boolean;
    private loginTime: Date;

    constructor(
        private context: ContextService,
        private apsc: ApscService,
        private i18n: I18nService,
        private users: UsersService
    ) {
        this._ = i18n._;
    }

    ngOnInit(){
        const { vars: {selectedUser}, user } = this.context;
        const { login, email, notificationEmail } = selectedUser;

        this.users.getLoginHistory(selectedUser, user).subscribe((loginTime: undefined | Date) => {
            this.loginTime = loginTime;
        });

        this.isAdmin = selectedUser.aps.type.includes("http://parallels.com/aps/types/pa/admin-user");
        this.isCurrentUser = user.aps.id === selectedUser.aps.id;
        this.isEmailHidden = login === email && (!notificationEmail || notificationEmail === email);
        this.isNotificationEmailHidden = this.isAdmin || !notificationEmail || (notificationEmail === email && notificationEmail === login);
        this.status = getStatus(selectedUser);
        this.hasLoginAsPermission = this.apsc.checkPrivilege(`http://www.parallels.com/pa/pa-core-services#${this.isAdmin ? "own_users-manage": "mycp_access"}`);
        this.hasManagePrivilege = !user.isAccountAdmin || this.apsc.checkPrivilege("http://www.parallels.com/pa/pa-core-services#own_account-manage");
    }
}

<aps-message
	*ngIf="disabled"
	[description]='_("The user has been disabled. He/she is not able to log in to Control Panel or use assigned services.")'
></aps-message>
<aps-message
		*ngIf="locked"
		[description]='_("The user has exceeded amount of allowed login attempts and got locked. Click Unlock to enable login back.")'
></aps-message>
<aps-message
	*ngIf="status === 'invited'"
	[description]='calculateDiff(context.vars.selectedUser.invitationDate) > 48
	 				? _("The user did not complete the activation. You need to resend an invitation, because the activation link has expired.")
	 				: _("The user did not yet complete the activation. The activation link emailed to the user, expires in 48 hours. If needed, you can resend an invitation.")'
></aps-message>
<aps-button
	*ngIf="hasManagePrivilege
	 		&& hasLoginAsPermission
	 		&& !isCurrentUser
	 		&& ['ready', 'updating', 'locked', 'disabled'].includes(status)"
	[label]='_("Login as ") + context.vars.selectedUser.givenName'
></aps-button>
<aps-button
	*ngIf="hasManagePrivilege
	 			&& !isCurrentUser
	 			&& ['ready', 'updating', 'locked', 'disabled'].includes(status)"
	[label]='_("Reset password")'
></aps-button>
<aps-button
	*ngIf="isCurrentUser && !context.vars.selectedUser.invitationDate"
	[label]='_("Change Password")'
></aps-button>
<aps-button
	*ngIf="!isAdmin || !isCurrentUser"
	[label]='_("Delete")'
></aps-button>
<aps-panel
	[title]='_("User Settings")'
>
	<aps-output
		[label]='_("Name")'
		[value]="context.vars.selectedUser.fullName"
	></aps-output>
	<aps-output
		[label]='_("Role")'
		[value]="isAdmin ? adminText : userText"
	></aps-output>
	<aps-output
		[label]='_("Phone")'
		[value]="context.vars.selectedUser.telWork"
	></aps-output>
	<aps-output
		[label]='_("Mobile Phone")'
		[value]="context.vars.selectedUser.telCell"
	></aps-output>
	<aps-output
		[label]='_("Language")'
		[value]="englishText"
	></aps-output>
	<aps-output
		[label]='isEmailHidden && isNotificationEmailHidden
		 			? _("Email")
		 			: _("Email (To Sign In)")'
		[value]="context.vars.selectedUser.login"
	></aps-output>
	<aps-output
		*ngIf="!isEmailHidden"
		[label]='_("Personal Email")'
		[value]="context.vars.selectedUser.email"
	></aps-output>
	<aps-output
		*ngIf="!isNotificationEmailHidden"
		[label]='_("Notification Email")'
		[value]="context.vars.selectedUser.notificationEmail"
	></aps-output>
</aps-panel>
<aps-panel
	[title]='_("Postal Address")'
>
	<aps-output
		[value]="context.vars.selectedUser.addressPostal.locality + ',' + context.vars.selectedUser.addressPostal.extendedAddress"
	></aps-output>
</aps-panel>
<aps-panel
	[title]='_("Login History")'
>
	<aps-output
		[label]="loginTime ? _('Last accessed') : ''"
		[value]='loginTime ? loginTime :
					(isCurrentUser
					 	? _("It’s the first time you logged in.")
					 	: _("This user has never logged in."))'
	></aps-output>
</aps-panel>

// react/pure/src/ui/UserView.js
import React, { Component } from 'react';

import Panel from '../platform/Panel';
import Button from '../platform/Button';
import Output from '../platform/Output';
import Message from '../platform/Message';

import _ from '../mocks/i18next';
import { checkPrivilege } from '../mocks/apsc';

function getStatus(user) {
	switch (user.aps.status) {
		case "aps:proto":
			return "creating";
		case "aps:configuring":
		case "aps:provisioning":
			return "updating";
		case "aps:unprovisioning":
			return "deleting";
		case "aps:deleted":
			return "deleted";
		case "aps:ready":
			if (!Array.isArray(user.services)) {
				console.warn("[ERROR] UserStatus cant resolve user services status: they were not loaded to model");
			} else
			if (user.services.some(function(service) {
				return	"aps:updating" === service.aps.status ||
					"aps:deleting" === service.aps.status ||
					"aps:provisioning" === service.aps.status ||
					"aps:configuring" === service.aps.status;
			})) {
				return "configuringServices";
			}

		default:
			if (user.disabled) {
				return "disabled";
			}

			if (user.locked) {
				return "locked";
			}

			if (!!user.invitationDate) {
				return "invited";
			}
	}

	return "ready";
}

function calculateDiff(invitationDate){
	const currentDate = new Date();
	invitationDate = new Date(invitationDate);
	const timeDiff = currentDate.getTime() - invitationDate.getTime();
	return Math.ceil(timeDiff / (1000 * 3600));
}

export default class UserView extends Component {
	constructor(props) {
		super(props);
		this.state = {
			loginTime: undefined
		};
	}

	async componentDidMount(){
		const { vars: {selectedUser}, user } = this.props.context;

		const response = await fetch(`/aps/2/resources/${selectedUser.aps.id}/loginHistory?sort(-loginTime),limit(${user.aps.id === selectedUser.aps.id ? "1" : "0"},1)`);
		const loginHistoryItems = await response.json();

		const lastLoginHistory = loginHistoryItems.length > 0 ? loginHistoryItems[0] : undefined;

		this.setState({
			loginTime: lastLoginHistory && new Date(lastLoginHistory.loginTime)
		});
	}

	render() {
		const { vars: {selectedUser}, user } = this.props.context;
		const { disabled, locked, invitationDate, telWork, telCell, login, email, notificationEmail, fullName, addressPostal, givenName } = selectedUser;
		const isAdmin = selectedUser.aps.type.includes("http://parallels.com/aps/types/pa/admin-user");
		const isCurrentUser = user.aps.id === selectedUser.aps.id;
		const isEmailHidden = login === email && (!notificationEmail || notificationEmail === email);
		const isNotificationEmailHidden = isAdmin || !notificationEmail || (notificationEmail === email && notificationEmail === login);
		const status = getStatus(selectedUser);
		const hasLoginAsPermission = checkPrivilege(`http://www.parallels.com/pa/pa-core-services#${isAdmin ? "own_users-manage": "mycp_access"}`);
		const hasManagePrivilege = !user.isAccountAdmin || checkPrivilege("http://www.parallels.com/pa/pa-core-services#own_account-manage");
		const loginTime = this.state.loginTime;

		return <div>
			{ (disabled || locked) && <Message bsStyle = "warning">
				{ disabled
					? _("The user has been disabled. He/she is not able to log in to Control Panel or use assigned services.")
					: _("The user has exceeded amount of allowed login attempts and got locked. Click Unlock to enable login back.") }
			</Message> }
			{ status === "invited" &&
				<Message bsStyle = "warning">
				{ calculateDiff(invitationDate) > 48
					? _("The user did not complete the activation. You need to resend an invitation, because the activation link has expired.")
					: _("The user did not yet complete the activation. The activation link emailed to the user, expires in 48 hours. If needed, you can resend an invitation.") }
			</Message> }
			{ hasManagePrivilege
				&& hasLoginAsPermission
				&& !isCurrentUser
				&& ["ready", "updating", "locked", "disabled"].includes(status)
				&& <Button
					bsStyle = "primary"
					label = {_(`Login as ${givenName }`)}
				/>
			}
			{ hasManagePrivilege
				&& !isCurrentUser
				&& ["ready", "updating", "locked", "disabled"].includes(status)
				&& <Button
					bsStyle = "primary"
					label = {_("Reset password")}
				/>
			}
			{ (isCurrentUser && !invitationDate) && <Button
				bsStyle = "primary"
				label = {_("Change Password")}
			/> }
			{ (!isAdmin || !isCurrentUser) && <Button
				bsStyle = "danger"
				label = {_("Delete")}
			/>}
			<Panel
				title = { _("User Settings") }
			>
				<Output label={_("Name")} value={fullName} />
				<Output label={_("Role")} value={isAdmin ? _("Admin") : _("User")} />
				<Output label={_("Phone")} value={telWork} />
				<Output label={_("Mobile Phone")} value={telCell} />
				<Output label={_("Language")} value={_("English (United States)")} />
				<Output
					label={ isEmailHidden && isNotificationEmailHidden ? _("Email") : _("Email (To Sign In)")}
					value={login}
				/>
				{!isEmailHidden && <Output label={_("Personal Email")} value={email} />}
				{!isNotificationEmailHidden && <Output label={_("Notification Email")} value={email} />}
			</Panel>
			<Panel
				title = { _("Postal Address") }
			>
				<Output value={`${addressPostal.locality}, ${addressPostal.extendedAddress}`} />
			</Panel>
			<Panel
				title = { _("Login History") }
			>
				<Output
					label={ loginTime && _("Last accessed")}
					value={ loginTime ? loginTime : (isCurrentUser ? _("It’s the first time you logged in.") : _("This user has never logged in.")) }
				/>
			</Panel>
		</div>;
	}
}
