// Angular/src/app/user-view/user-view.component.ts
/* Example of View with ajax */

import { Component, OnInit } from '@angular/core';
import { ContextService, ApscService } from '@aps';
import {UsersService} from "../users.service";

function getStatus(user) {
    switch (user.aps.status) {
        case "aps:proto":
            return "creating";
        case "aps:configuring":
        case "aps:provisioning":
            return "updating";
        case "aps:unprovisioning":
            return "deleting";
        case "aps:deleted":
            return "deleted";
        case "aps:ready":
            if (!Array.isArray(user.services)) {
                console.warn("[ERROR] UserStatus cant resolve user services status: they were not loaded to model");
            } else
            if (user.services.some(function(service) {
                return	"aps:updating" === service.aps.status ||
                    "aps:deleting" === service.aps.status ||
                    "aps:provisioning" === service.aps.status ||
                    "aps:configuring" === service.aps.status;
            })) {
                return "configuringServices";
            }

        default:
            if (user.disabled) {
                return "disabled";
            }

            if (user.locked) {
                return "locked";
            }

            if (!!user.invitationDate) {
                return "invited";
            }
    }

    return "ready";
}

@Component({
    selector: 'user-view',
    templateUrl: './user-view.component.html'
})
export class UserViewComponent implements OnInit {
    private _: (text: string) => string;
    private hasLoginAsPermission: boolean;
    private hasManagePrivilege: boolean;
    private status: string;
    private isNotificationEmailHidden: boolean;
    private isEmailHidden: boolean;
    private isCurrentUser: boolean;
    private isAdmin: boolean;
    private loginTime: Date;

    constructor(
        private context: ContextService,
        private apsc: ApscService,
        private users: UsersService
    ) {}

    ngOnInit(){
        const { vars: {selectedUser}, user } = this.context;
        const { login, email, notificationEmail } = selectedUser;

        this.users.getLoginHistory(selectedUser, user).subscribe((loginTime: undefined | Date) => {
            this.loginTime = loginTime;
        });

        this.isAdmin = selectedUser.aps.type.includes("http://parallels.com/aps/types/pa/admin-user");
        this.isCurrentUser = user.aps.id === selectedUser.aps.id;
        this.isEmailHidden = login === email && (!notificationEmail || notificationEmail === email);
        this.isNotificationEmailHidden = this.isAdmin || !notificationEmail || (notificationEmail === email && notificationEmail === login);
        this.status = getStatus(selectedUser);
        this.hasLoginAsPermission = this.apsc.checkPrivilege(`http://www.parallels.com/pa/pa-core-services#${this.isAdmin ? "own_users-manage": "mycp_access"}`);
        this.hasManagePrivilege = !user.isAccountAdmin || this.apsc.checkPrivilege("http://www.parallels.com/pa/pa-core-services#own_account-manage");
    }

    calculateDiff(invitationDate){
        const currentDate = new Date();
        invitationDate = new Date(invitationDate);
        const timeDiff = currentDate.getTime() - invitationDate.getTime();
        return Math.ceil(timeDiff / (1000 * 3600));
    }
}

<aps-message
	*ngIf="disabled"
	[description]='"The user has been disabled. He/she is not able to log in to Control Panel or use assigned services." | translate'
></aps-message>
<aps-message
		*ngIf="locked"
		[description]='"The user has exceeded amount of allowed login attempts and got locked. Click Unlock to enable login back." | translate'
></aps-message>
<aps-message
	*ngIf="status === 'invited'"
	[description]='calculateDiff(context.vars.selectedUser.invitationDate) > 48
	 				? ("The user did not complete the activation. You need to resend an invitation, because the activation link has expired." | translate)
	 				: ("The user did not yet complete the activation. The activation link emailed to the user, expires in 48 hours. If needed, you can resend an invitation." | translate)'
></aps-message>
<aps-button
	*ngIf="hasManagePrivilege
	 		&& hasLoginAsPermission
	 		&& !isCurrentUser
	 		&& ['ready', 'updating', 'locked', 'disabled'].includes(status)"
	[label]='("Login as " | translate) + context.vars.selectedUser.givenName'
></aps-button>
<aps-button
	*ngIf="hasManagePrivilege
	 			&& !isCurrentUser
	 			&& ['ready', 'updating', 'locked', 'disabled'].includes(status)"
	[label]='"Reset password" | translate'
></aps-button>
<aps-button
	*ngIf="isCurrentUser && !context.vars.selectedUser.invitationDate"
	[label]='"Change Password" | translate'
></aps-button>
<aps-button
	*ngIf="!isAdmin || !isCurrentUser"
	[label]='"Delete" | translate'
></aps-button>
<aps-panel
	[title]='"User Settings" | translate'
>
	<aps-output
		[label]='"Name" | translate'
		[value]="context.vars.selectedUser.fullName"
	></aps-output>
	<aps-output
		[label]='"Role" | translate'
		[value]="isAdmin ? adminText : userText"
	></aps-output>
	<aps-output
		[label]='"Phone" | translate'
		[value]="context.vars.selectedUser.telWork"
	></aps-output>
	<aps-output
		[label]='"Mobile Phone" | translate'
		[value]="context.vars.selectedUser.telCell"
	></aps-output>
	<aps-output
		[label]='"Language" | translate'
		[value]="englishText"
	></aps-output>
	<aps-output
		[label]='isEmailHidden && isNotificationEmailHidden
		 			? ("Email" | translate)
		 			: ("Email (To Sign In)" | translate)'
		[value]="context.vars.selectedUser.login"
	></aps-output>
	<aps-output
		*ngIf="!isEmailHidden"
		[label]='"Personal Email" | translate'
		[value]="context.vars.selectedUser.email"
	></aps-output>
	<aps-output
		*ngIf="!isNotificationEmailHidden"
		[label]='"Notification Email" | translate'
		[value]="context.vars.selectedUser.notificationEmail"
	></aps-output>
</aps-panel>
<aps-panel
	[title]='"Postal Address" | translate'
>
	<aps-output
		[value]="context.vars.selectedUser.addressPostal.locality + ',' + context.vars.selectedUser.addressPostal.extendedAddress"
	></aps-output>
</aps-panel>
<aps-panel
	[title]='"Login History" | translate'
>
	<aps-output
		[label]="loginTime ? ('Last accessed' | translate) : ''"
		[value]='loginTime ? loginTime :
					(isCurrentUser
					 	? ("It’s the first time you logged in." | translate)
					 	: ("This user has never logged in." | translate))'
	></aps-output>
</aps-panel>

// React/redux/src/ui/UserView/index.js
/* Example of View with ajax */

import React, { Component } from 'react';

import Panel from '../../platform/Panel';
import Button from '../../platform/Button';
import Output from '../../platform/Output';
import Message from '../../platform/Message';
import { context } from '../../platform/props';

import _ from '../../platform/mocks/i18next';
import { checkPrivilege } from '../../platform/mocks/apsc';

import { actions } from './model';
import {connect} from "react-redux";

function getStatus(user) {
	switch (user.aps.status) {
		case "aps:proto":
			return "creating";
		case "aps:configuring":
		case "aps:provisioning":
			return "updating";
		case "aps:unprovisioning":
			return "deleting";
		case "aps:deleted":
			return "deleted";
		case "aps:ready":
			if (!Array.isArray(user.services)) {
				console.warn("[ERROR] UserStatus cant resolve user services status: they were not loaded to model");
			} else
			if (user.services.some(function(service) {
				return	"aps:updating" === service.aps.status ||
					"aps:deleting" === service.aps.status ||
					"aps:provisioning" === service.aps.status ||
					"aps:configuring" === service.aps.status;
			})) {
				return "configuringServices";
			}

		default:
			if (user.disabled) {
				return "disabled";
			}

			if (user.locked) {
				return "locked";
			}

			if (!!user.invitationDate) {
				return "invited";
			}
	}

	return "ready";
}

function calculateDiff(invitationDate){
	const currentDate = new Date();
	invitationDate = new Date(invitationDate);
	const timeDiff = currentDate.getTime() - invitationDate.getTime();
	return Math.ceil(timeDiff / (1000 * 3600));
}

function MessageList({ disabled, locked, status, invitationDate}){
	return <React.Fragment>
		{ disabled &&
		<Message bsStyle = "warning">
			{ _("The user has been disabled. He/she is not able to log in to Control Panel or use assigned services.") }
		</Message> }
		{ locked &&
		<Message bsStyle = "warning">
			{ _("The user has exceeded amount of allowed login attempts and got locked. Click Unlock to enable login back.") }
		</Message>}
		{ status === "invited" &&
		<Message bsStyle = "warning">
			{ calculateDiff(invitationDate) > 48
				? _("The user did not complete the activation. You need to resend an invitation, because the activation link has expired.")
				: _("The user did not yet complete the activation. The activation link emailed to the user, expires in 48 hours. If needed, you can resend an invitation.") }
		</Message> }
	</React.Fragment>;
}

function Toolbar({ hasManagePrivilege, hasLoginAsPermission, isCurrentUser, btnStatus, givenName, isAdmin }) {
	return <React.Fragment>
		{ hasManagePrivilege
		&& hasLoginAsPermission
		&& !isCurrentUser
		&& btnStatus
		&& <Button
			bsStyle = "primary"
			label = {_(`Login as ${givenName }`)}
		/>
		}
		{ hasManagePrivilege
		&& !isCurrentUser
		&& btnStatus
		&& <Button
			bsStyle = "primary"
			label = {_("Reset password")}
		/>
		}
		{ (isCurrentUser && !invitationDate) && <Button
			bsStyle = "primary"
			label = {_("Change Password")}
		/>
		}
		{ (!isAdmin || !isCurrentUser) && <Button
			bsStyle = "danger"
			label = {_("Delete")}
		/> }
	</React.Fragment>
}

function UserSettings({ isAdmin, user: { fullName, telWork, telCell, login, email, notificationEmail } }) {
	const isEmailHidden = login === email && (!notificationEmail || notificationEmail === email);
	const isNotificationEmailHidden = isAdmin || !notificationEmail || (notificationEmail === email && notificationEmail === login);

	return <Panel
		title = { _("User Settings") }
	>
		<Output label={_("Name")} value={fullName} />
		<Output label={_("Role")} value={isAdmin ? _("Admin") : _("User")} />
		<Output label={_("Phone")} value={telWork} />
		<Output label={_("Mobile Phone")} value={telCell} />
		<Output label={_("Language")} value={_("English (United States)")} />
		<Output
			label={ isEmailHidden && isNotificationEmailHidden ? _("Email") : _("Email (To Sign In)")}
			value={login}
		/>
		{!isEmailHidden && <Output label={_("Personal Email")} value={email} />}
		{!isNotificationEmailHidden && <Output label={_("Notification Email")} value={notificationEmail} />}
	</Panel>;
}

class UserView extends Component {
	componentDidMount(){
		this.props.dispatch(actions.requestHistory(this.props.context));
	}

	render() {
		const { vars: {selectedUser}, user } = this.props.context;
		const { disabled, locked, invitationDate, addressPostal, givenName } = selectedUser;
		const isAdmin = selectedUser.aps.type.includes("http://parallels.com/aps/types/pa/admin-user");
		const isCurrentUser = user.aps.id === selectedUser.aps.id;
		const status = getStatus(selectedUser);
		const loginTime = this.props.loginTime;

		return <React.Fragment>
			<MessageList
				disabled = { disabled }
				locked = {locked}
				status = {status}
				invitationDate = {invitationDate}
			/>
			<Toolbar
				hasManagePrivilege = {
					!user.isAccountAdmin || checkPrivilege("http://www.parallels.com/pa/pa-core-services#own_account-manage")
				}
				hasLoginAsPermission = {
					checkPrivilege(`http://www.parallels.com/pa/pa-core-services#${isAdmin ? "own_users-manage": "mycp_access"}`)
				}
				isCurrentUser = { isCurrentUser }
				btnStatus = { ["ready", "updating", "locked", "disabled"].includes(status) }
				givenName = { givenName }
				isAdmin = { isAdmin }
			/>
			<UserSettings
				isAdmin = { isAdmin }
				user = { selectedUser }
			/>
			<Panel title = { _("Postal Address") }>
				<Output value={`${addressPostal.locality}, ${addressPostal.extendedAddress}`} />
			</Panel>
			<Panel title = { _("Login History") }>
				<Output
					label={ loginTime && _("Last accessed")}
					value={ loginTime ? loginTime : (isCurrentUser ? _("It’s the first time you logged in.") : _("This user has never logged in.")) }
				/>
			</Panel>
		</React.Fragment>;
	}
}

UserView.propTypes = {
	context
};

const UserViewConnected = connect(state => state.userViewState)(UserView);

export default ({context}) => {
	return <UserViewConnected context = { context } />;
};
