// Angular/src/app/edit-view/edit-view.component.ts
/* Example of View with forms */

import { Component } from '@angular/core';
import {ContextService} from '@aps';
import { UsersService } from "../users.service";

@Component({
  selector: 'edit-view',
  templateUrl: './edit-view.component.html'
})
export class EditViewComponent {
  services: string[] = [];
  sendInvitation = false;

  constructor(
      private context: ContextService,
      private users: UsersService
  ) {}

  private servicesUpdate(status: boolean, serviceId: string, i: number){
    if (status) {
      this.services.push(serviceId);
    } else {
      this.services.splice(i, 1);
    }
  }
}

<poc-edit-user-form *ngFor="let user of users.users; let i = index"
                               [user]="user"
                               [id]="user.id"
                               (onAddUser)="users.addUser()"
                               (onRemoveUser)="users.removeUser(i)"
                               [needRemove]="users.users.length !== 1"
                               [needAdd]="i + 1 === users.users.length"></poc-edit-user-form>
<aps-panel [title]='"Assign Services To New User" | translate'>
  <aps-checkbox *ngFor="let serviceItem of context.wizardState; let i = index"
                [checked]="services.includes(serviceItem.id)"
                [description]="serviceItem.label"
                (checkedChange)="servicesUpdate($event, serviceItem.id, i)">
    {{serviceItem.label}}
  </aps-checkbox>
</aps-panel>
<aps-panel [title]='"Select Options" | translate'>
  <aps-checkbox [description]='"Send activation email to users" | translate'
                [hint]='"Users will be given an activation link to log in to the Control Panel and enable services assigned." | translate'
                [(checked)]="sendInvitation">
  </aps-checkbox>
</aps-panel>

// React/redux/src/ui/EditView/index.js
/* Example of View with forms */

import React, { Component } from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';

import Panel from '../../platform/Panel';
import CheckBox from '../../platform/CheckBox';
import { context } from '../../platform/props';

import _ from '../../platform/mocks/i18next';

import EditUserForm from '../components/EditUserForm';
import { actions } from './model';
import userTemplate from './userTemplate';

class EditView extends Component {
	render(){
		const {
			context: {wizardState=[]},
			users, services, options,
			servicesActions, optionsActions, usersActions
		} = this.props;

		return <React.Fragment>
			{ users.map((user, i) => {
				return <EditUserForm
					key = { user.id }
					user = {user}
					needRemove = { users.length !== 1 }
					needAdd = { i+1 === users.length }
					onRemoveUser = { () => {
						usersActions.removeUser(i);
					} }
					onAddUser = { () => {
						usersActions.addUser({ id: users.length, ...userTemplate });
					} }
					onUserChange = { (user) => {
						usersActions.changeUser(user);
					} }
				/>;
			}) }
			<Panel title = { _("Assign Services To New User") }>
				{ wizardState.map((serviceItem, i) => {
					return <CheckBox
						key = { serviceItem.id }
						description = { serviceItem.label }
						checked = { services.includes(serviceItem.id) }
						onChange = {e => {
							servicesActions[e.target.checked ? "assignService" : "unassignService"](serviceItem.id);
						}}
					/>;
				}) }
			</Panel>
			<Panel title = { _("Select Options") }>
				<CheckBox
					description = { _("Send activation email to users") }
					hint = { _("Users will be given an activation link to log in to the Control Panel and enable services assigned.") }
					checked = { options.sendInvitation }
					onChange = { (e) => optionsActions.setSendInvitation(e.target.checked) }
				/>
			</Panel>
		</React.Fragment>;
	}
}

EditView.propTypes = {
	context
};

function mapDispatchToProps(dispatch){
	return {
		optionsActions: bindActionCreators(actions.options, dispatch),
		servicesActions: bindActionCreators(actions.services, dispatch),
		usersActions: bindActionCreators(actions.users, dispatch)
	};
}

const EditViewConnected = connect(state => state.editViewState, mapDispatchToProps)(EditView);

export default ({context}) => {
	return <EditViewConnected context = { context } />;
};
