// React/mobx/src/platform/Output.js
import React from 'react';
import { FormGroup, ControlLabel, HelpBlock } from 'react-bootstrap';
import { string, number, oneOfType } from 'prop-types';

const Output = ({ id, label, description, value }) => {
	return <FormGroup controlId={id}>
		{label && <ControlLabel>{label}</ControlLabel>}
		<div className="input-group">
			<p className="form-control-static text-default">
				{ typeof value === "string" ? value : value.toString() }
			</p>
		</div>
		{description && <HelpBlock>{description}</HelpBlock>}
	</FormGroup>;
};

Output.propTypes = {
	id: oneOfType([number, string]),
	description: string,
	label: string,
	value: string
};

export default Output;

// Angular/projects/aps/src/lib/ui/output/output.component.ts
import { Input, Component } from '@angular/core';

@Component({
    selector: 'aps-output',
    templateUrl: './output.component.html'
})
export class OutputComponent {
    @Input() label: string;
    @Input() description: string;
    @Input() value: string;
}
<div class="form-group">
	<label class="control-label" *ngIf="label">
		{{label}}
	</label>
	<div class="input-group">
		<p class="form-control-static text-default">{{value}}</p>
	</div>
	<small class="help-block" *ngIf="description">
		{{description}}
	</small>
</div>
