// Angular/src/ui/components/EditUserForm/EditUserForm.ts
import { Input, Component, Output, EventEmitter } from '@angular/core';

enum UserType { User='User', Admin='Admin' }

interface User {
    id:                     number;
    givenName:              string;
    familyName:             string;
    type: 		            UserType;
    login: 		            string;
    notificationEmail:      string;
    hasNotificationEmail:   boolean;
    sendInvitation:         boolean;
}

interface Option {
    label: UserType,
    value: UserType
}

@Component({
    selector: 'poc-editUserForm',
    templateUrl: './EditUserForm.template.html'
})
export default class EditUserForm {
    @Input() id: string;
    @Input() user: User;
    @Input() needAdd: boolean;
    @Input() needRemove: boolean;

    @Output() onAddUser = new EventEmitter();
    addUser() {
        this.onAddUser.emit();
    }
    @Output() onRemoveUser = new EventEmitter();
    removeUser() {
        this.onRemoveUser.emit();
    }

    private userTypes: Option[] = [
        { label: UserType.User, value: UserType.User },
        { label: UserType.Admin, value: UserType.Admin }
    ];
    private title: string = "Specify New User";
    private firstNameLabel: string = "First Name";
    private firstNamePlaceholder: string = "e.g.: John";
    private lastNameLabel: string = "Last Name";
    private lastNamePlaceholder: string = "e.g.: Smith";
    private roleNameLabel: string = "Role Name";
    private addUserText: string = "On More User";
    private removeUserText: string = "Remove User";
    private emailNameText: string = "Email Name";
    private emailToSignInText: string = "Email (To Sign In)";
    private emailPlaceholder: string = "e.g.: john@mycompany.com";
    private emailNameDescription: string = "This email address will be used to sign in and receive notifications.";
    private emailToSignInDescription: string = "You'll use it to sign in.";
    private notificationEmailText: string = "Notification Email";
    private notificationEmailDescription: string = "We'll use this email for account and system updates.";
    private diffrentEmailText: string = "Use different emails to sign in and receive notifications.";
}

// React/pure/src/ui/components/EditUserForm.js
import React from 'react';

import _ from "../../mocks/i18next";

import Panel from '../../platform/Panel';
import TextBox from '../../platform/TextBox';
import CheckBox from '../../platform/CheckBox';
import Select from '../../platform/Select';
import Button from '../../platform/Button';

const EditUserForm = ({ user, needRemove, needAdd, onRemoveUser, onAddUser, onUserChange }) => {
	const hasNotificationEmail = user.hasNotificationEmail;

	return <Panel
		key={user.id}
		id={user.id}
		title={_("Specify New User")}
	>
		<TextBox
			label={_("First Name")}
			placeholder={_("e.g.: John")}
			value={user.givenName}
			onChange={(e) => {
				user.givenName = e.target.value;
				onUserChange(user);
			}}
		/>
		<TextBox
			label={_("Last Name")}
			placeholder={_("e.g.: Smith")}
			value={user.familyName}
			onChange={(e) => {
				user.familyName = e.target.value;
				onUserChange(user);
			}}
		/>
		<Select
			label={_("Role Name")}
			options={[
				{label: "User", value: "User"},
				{label: "Admin", value: "Admin"}
			]}
			value={user.type}
			onChange={(e) => {
				user.type = e.target.value;
				onUserChange(user);
			}}
		/>
		<TextBox
			label={hasNotificationEmail ? _("Email Name") : _("Email (To Sign In)")}
			placeholder={_("e.g.: john@mycompany.com")}
			description={
				hasNotificationEmail
					? _("This email address will be used to sign in and receive notifications.")
					: _("You'll use it to sign in.")
			}
			value={user.login}
			onChange={(e) => {
				user.login = e.target.value;
				onUserChange(user);
			}}
		/>
		{hasNotificationEmail && <TextBox
			description={_("We'll use this email for account and system updates.")}
			placeholder={_("e.g.: john@mycompany.com")}
			label={_("Notification Email")}
			value={user.notificationEmail}
			onChange={(e) => {
				user.notificationEmail = e.target.value;
				onUserChange(user);
			}}
		/>}
		<CheckBox
			description={_("Use different emails to sign in and receive notifications.")}
			checked={user.hasNotificationEmail}
			onChange={(e) => {
				user.hasNotificationEmail = e.target.checked;
				onUserChange(user);
			}}
		/>
		{needAdd && <Button
			bsStyle="primary"
			label={_("On More User")}
			onClick={onAddUser}
		/>}
		{needRemove && <Button
			label={_("Remove User")}
			onClick={onRemoveUser}
		/>}
	</Panel>;
};

export default EditUserForm;
