// Angular/src/app/edit-user-form/edit-user-form.component.ts
/* Example of custom component */

import { Component, EventEmitter, Input, Output } from '@angular/core';
import { User } from '../users/user';
import { UserType } from '../users/user-type';

interface Option {
  label: UserType;
  value: UserType;
}

@Component({
  selector: 'poc-edit-user-form',
  templateUrl: './edit-user-form.component.html'
})
export class EditUserFormComponent {
  private userTypes: Option[] = [
    { label: UserType.User, value: UserType.User },
    { label: UserType.Admin, value: UserType.Admin }
  ];

  @Input() id: string;
  @Input() user: User;
  @Input() needAdd: boolean;
  @Input() needRemove: boolean;

  @Output() onAddUser = new EventEmitter();
  @Output() onRemoveUser = new EventEmitter();

  addUser() {
    this.onAddUser.emit();
  }

  removeUser() {
    this.onRemoveUser.emit();
  }

}

<aps-panel
      [title]='"Specify New User" | translate'
      [id]="id"
>
    <aps-textbox
        [label]="'First Name' | translate"
        [placeholder]='"e.g.: John" | translate'
        [(value)]="user.givenName"
    ></aps-textbox>
    <aps-textbox
        [label]='"Last Name" | translate'
        [placeholder]='"e.g.: Smith" | translate'
        [(value)]="user.familyName"
    ></aps-textbox>
    <aps-select
        [label]='"Role Name" | translate'
        [(value)]="user.type"
        [options]="userTypes"
    ></aps-select>
    <aps-textbox
        [label]='user.hasNotificationEmail ? ("Email Name" | translate) : ("Email (To Sign In)" | translate)'
        [placeholder]='"e.g.: john@mycompany.com" | translate'
        [description]='user.hasNotificationEmail
                            ? ("This email address will be used to sign in and receive notifications." | translate)
                            : ("You`ll use it to sign in." | translate)'
        [(value)]="user.login"
    ></aps-textbox>
    <aps-textbox
        *ngIf="user.hasNotificationEmail"
        [label]='"Notification Email" | translate'
        [placeholder]='"e.g.: john@mycompany.com" | translate'
        [description]='"We`ll use this email for account and system updates." | translate'
        [(value)]="user.notificationEmail"
    ></aps-textbox>
    <aps-checkbox
        [description]='"Use different emails to sign in and receive notifications." | translate'
        [(checked)]="user.hasNotificationEmail"
    ></aps-checkbox>
    <aps-button
        *ngIf="needAdd"
        (onClicked)="addUser()"
        [label]='"On More User" | translate'
    ></aps-button>
    <aps-button
        *ngIf="needRemove"
        (onClicked)="removeUser(i)"
        [label]='"Remove User" | translate'
    ></aps-button>
</aps-panel>

// react/pure/src/ui/components/EditUserForm.js
import React from 'react';

import update from 'immutability-helper';

import _ from "../../mocks/i18next";

import Panel from '../../platform/Panel';
import TextBox from '../../platform/TextBox';
import CheckBox from '../../platform/CheckBox';
import Select from '../../platform/Select';
import Button from '../../platform/Button';

const EditUserForm = ({ user, needRemove, needAdd, onRemoveUser, onAddUser, onUserChange }) => {
	const hasNotificationEmail = user.hasNotificationEmail;

	return <Panel
		key={user.id}
		id={user.id}
		title={_("Specify New User")}
	>
		<TextBox
			label={_("First Name")}
			placeholder={_("e.g.: John")}
			value={user.givenName}
			onChange={(e) => {
				onUserChange(update(user, { givenName: { $set: e.target.value } }));
			}}
		/>
		<TextBox
			label={_("Last Name")}
			placeholder={_("e.g.: Smith")}
			value={user.familyName}
			onChange={(e) => {
				onUserChange(update(user, { familyName: { $set: e.target.value } }));
			}}
		/>
		<Select
			label={_("Role Name")}
			placeholder={_("e.g.: John")}
			options={[
				{label: "User", value: "User"},
				{label: "Admin", value: "Admin"}
			]}
			value={user.type}
			onChange={(e) => {
				onUserChange(update(user, { type: { $set: e.target.value } }));
			}}
		/>
		<TextBox
			label={hasNotificationEmail ? _("Email Name") : _("Email (To Sign In)")}
			placeholder={_("e.g.: John")}
			description={
				hasNotificationEmail
					? _("This email address will be used to sign in and receive notifications.")
					: _("You'll use it to sign in.")
			}
			value={user.login}
			onChange={(e) => {
				onUserChange(update(user, { login: { $set: e.target.value } }));
			}}
		/>
		{hasNotificationEmail && <TextBox
			description={_("We'll use this email for account and system updates.")}
			label={_("Notification Email")}
			value={user.notificationEmail}
			onChange={(e) => {
				onUserChange(update(user, { notificationEmail: { $set: e.target.value } }));
			}}
		/>}
		<CheckBox
			description={_("Use different emails to sign in and receive notifications.")}
			checked={user.hasNotificationEmail}
			onChange={(e) => {
				onUserChange(update(user, { hasNotificationEmail: { $set: e.target.checked } }));
			}}
		/>
		{needAdd && <Button
			bsStyle="primary"
			label={_("On More User")}
			onClick={onAddUser}
		/>}
		{needRemove && <Button
			label={_("Remove User")}
			onClick={onRemoveUser}
		/>}
	</Panel>;
};

export default EditUserForm;
